### PR TITLE
docs(sphinx): Add custom CLI documentation process

### PR DESCRIPTION
**Pull request by santiagogaray**
Hi @chriswmackey,

I think we have this process at a decent point where we can include it to this repo. 
I everything is good I believe I'm running out of repos to update the CLI docs. or add sphinx docs to at this point. Let me know if you would like to add any work (we skipped three repos and we only added one so far). Otherwise I could start working on the gitbook project if that's okay with you!

### CODE REVIEW

**Comment by chriswmackey** [comment]
Thanks, @santiagogaray . This looks good but I will hold off om merging right now in case we want to add support for the case over here:
https://github.com/ladybug-tools/honeybee-radiance-folder/pull/85

**Comment by chriswmackey** [comment]
Also, working on the component GitBooks next would be awesome!

**Comment by santiagogaray** [comment]
Sounds good @chriswmackey,

I can update with latest in https://github.com/ladybug-tools/honeybee-radiance-folder/pull/85 if that gets approved!

**Comment by santiagogaray** [comment]
Hi @chriswmackey,
If you are okay, I believe we can now update conf.py with the latest process.

**Review by chriswmackey — CHANGES_REQUESTED** [review]
This is generally looking great. Thanks, @santiagogaray .

There's just one change that I think we need to make before merging and that's adding `sphinx-click==2.7.1` to the dev-requirements.txt here:

https://github.com/ladybug-tools/ladybug-tools-template/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/dev-requirements.txt

Once you add this, then we can merge.

**Comment by chriswmackey** [comment]
Also, I gave you triage access on the repo here so you should be able to request my review now.

**Comment by santiagogaray** [comment]
Thanks @chriswmackey for the pointer. I hope this is good to go!

**Review by chriswmackey — APPROVED** [review]
Thanks, @santiagogaray . This is great. Merged!

**Pull request merged**
